w_dict={ ' ::POOF:: ':' goodbye - leaving the room ' , 
' <3 ':' heart ' , 
' 1 ':' one or won ' , 
' 112 ':' European emergency number ' , 
' 12 ':' the police ' , 
' 143 ':' I Love You (One Letter or Four Letters or 3 Letters) ' , 
' 187 ':' police code for murder or death ' , 
' 1AAT ':' one at a time ' , 
' 2 ':' to or too or two ' , 
' 211 ':' police code for robbery ' , 
' 220 ':' second to none ' , 
' 224 ':' today or tomorrow or forever ' , 
' 241 ':' two for one ' , 
' 2B ':' to be ' , 
' 2BH ':' to be honest ' , 
' 2D4 ':' to die for ' , 
' 2DAY ':' today ' , 
' 2EZ ':' too easy ' , 
' 2G4U ':' too good for you ' , 
' 2L8 ':' too late ' , 
' 2M/2MORO/2MRW ':' tomorrow ' , 
' 381 ':' I love you (3 words or 8 letters or 1 meaning) ' , 
' 4 ':' for or four ' , 
' 404 ':' I haven t a clue (Internet error message - page not found) ' , 
' 411 ':' Information ' , 
' 420 ':' Drugs ' , 
' 4COL ':' for crying out loud ' , 
' 4E ':' forever ' , 
' 4GET ':' forget ' , 
' 4GM ':' forgive me ' , 
' 4M ':' forum ' , 
' 4RL? ':' for real? ' , 
' 4SHO ':' for sure ' , 
' 4SRS ':' for serious ' , 
' 4U ':' for you ' , 
' 4WARD ':' forward ' , 
' 4WIW ':' for what it s worth ' , 
' 4YEO ':' for your eyes only ' , 
' 50 ':' police (from Hawaii 50) ' , 
' 5150 ':' police code for crazy person on the loose ' , 
' 7DAW ':' seven days a week ' , 
' 9 ':' parents watching ' , 
' 911 ':' US emergency number ' , 
' 99 ':' parents stopped watching ' , 
' 999 ':' UK emergency number ' , 
' ADN ':' any day now ' , 
' A&F ':' always and forever/Abercrombie & Fitch ' , 
' A/W ':' anyway ' , 
' A3 ':' anytime or anywhere or anyplace ' , 
' AAB ':' average at best ' , 
' AAF ':' always and forever ' , 
' AAK ':' alive and kicking ' , 
' AAMOF ':' as a matter of fact ' , 
' AAP ':' always a pleasure ' , 
' AAR ':' at any rate ' , 
' AAT ':' and another thing/at all times ' , 
' AAWY ':' and also with you ' , 
' AAYF ':' as always or your friend ' , 
' AB ':' about ' , 
' ABD ':' already been done ' , 
' ABF ':' all but face ' , 
' ABH ':' actual bodily harm ' , 
' ABP ':' already been posted ' , 
' ABS ':' absolutely ' , 
' ABT ':' about ' , 
' ABT2 ':' about to ' , 
' ACP ':' automatic Colt pistol ' , 
' ADDY ':' address ' , 
' ADL ':' all day long ' , 
' AEAP ':' as early as possible ' , 
' AFAIAC/AFAIC ':' as far as I am (I m) concerned ' , 
' AFAICS ':' as far as I can see ' , 
' AFAICT ':' as far as I can tell ' , 
' AFAIK ':' as far as I know ' , 
' AFAIR ':' as far as I remember ' , 
' AFAP ':' as far as possible ' , 
' AFC ':' away from computer ' , 
' AFF ':' affirmative ' , 
' AFK ':' away from keyboard ' , 
' AFN ':' all for now ' , 
' AFP ':' away from phone ' , 
' AFS ':' always or forever or and seriously ' , 
' AG ':' aggressive ' , 
' AGGY ':' aggitated ' , 
' AGH ':' ain t gonna happen ' , 
' AGW ':' all going well ' , 
' AIGF ':' all in good fun ' , 
' AINEC ':' and it s not even close ' , 
' AIO ':' all-in-one ' , 
' AISB ':' as I said before ' , 
' AISI ':' as I see it ' , 
' AITR ':' adult in the room ' , 
' AITYD ':' and I think you do ' , 
' AIUI ':' as I understand it ' , 
' AKTF ':' always keep the faith ' , 
' AL ':' alcohol ' , 
' ALAP ':' as late/long/little as possible ' , 
' ALG ':' is life not grand ' , 
' ALIHAL ':' at least I have a life ' , 
' ALOL ':' actually laughing out loud ' , 
' ALOTBSOL ':' always look on the bright side of life ' , 
' AMA ':' ask me anything/against medical advice ' , 
' AMAP ':' as much/many as possible ' , 
' AMIIC ':' ask me if I care ' , 
' AML ':' all my love ' , 
' AMOG ':' alpha male of group ' , 
' AMZ ':' amazing ' , 
' ANFAWFOS ':' and now for a word from our sponsor ' , 
' ANFSCD ':' and now for something completely different ' , 
' ANON ':' unknown person ' , 
' ANS ':' answer ' , 
' ANY1 ':' anyone ' , 
' AO ':' adults only ' , 
' AOB ':' any other business ' , 
' AON ':' all or nothing/as of now ' , 
' AOS ':' ahead of schedule ' , 
' AOT ':' as opposed to/among other things ' , 
' AOTA ':' all of the above ' , 
' AOW ':' all out war ' , 
' APO ':' authorized personnel only ' , 
' APU ':' as per usual ' , 
' AQAP ':' as quickly as possible ' , 
' ARE ':' acronym-rich environment ' , 
' ARK ':' act of random kindness ' , 
' ASAIC ':' as soon as I can ' , 
' ASAP ':' as soon as possible ' , 
' ASF ':' and so forth ' , 
' ASL ':' age? sex? location? ' , 
' ASLP ':' ag or sex or location or picture? ' , 
' ASN ':' any second now ' , 
' ASP ':' at some point ' , 
' ATB ':' all the best ' , 
' ATEOTD ':' at the end of the day ' , 
' ATF ':' all time favorite ' , 
' ATK ':' attack ' , 
' ATM ':' at the moment ' , 
' ATMO ':' according to my opinion ' , 
' ATN ':' any time now ' , 
' ATQ ':' answer the question ' , 
' ATST ':' at the same time ' , 
' ATT ':' at this time/all the time ' , 
' ATTT ':' ain t that the truth ' , 
' ATVB ':' all the very best ' , 
' ATW ':' all the way ' , 
' ATW ':' at the weekend ' , 
' ATYS ':' anything you say ' , 
' AUP ':' another useless post/acceptable use policy ' , 
' AWA ':' as well as ' , 
' AWHFY ':' are we having fun yet? ' , 
' AWNP ':' all work or no play ' , 
' AWS ':' as we speak ' , 
' AWSM ':' awesome ' , 
' AWW ':' any which way ' , 
' AYCS ':' as you can see ' , 
' AYEC ':' at your earliest convenience ' , 
' AYFKMWTS ':' are you f***ing kidding me with this s***? ' , 
' AYFR ':' are you for real? ' , 
' AYFT ':' are you free today? ' , 
' AYK ':' as you know ' , 
' AYKM ':' are you kidding me? ' , 
' AYL ':' are you listening? ' , 
' AYOR ':' at your own risk ' , 
' AYPI ':' and your point is? ' , 
' AYS ':' are you serious? ' , 
' AYSOS ':' are you stupid or something? ' , 
' AYT ':' are you there? ' , 
' AYW ':' as you wish ' , 
' B ':' be ' , 
' B/C ':' because ' , 
' B/W ':' between ' , 
' B2B ':' back to back ' , 
' B2W ':' back to work ' , 
' B4 ':' before ' , 
' B4N ':' bye for now ' , 
' B8 ':' bait ' , 
' BAC ':' back at computer/by any change ' , 
' BAGL ':' bust a gut laughing ' , 
' BAH ':' bored as hell ' , 
' BAK ':' back at keyboard ' , 
' BAM ':' below average mentality ' , 
' BAMN ':' by any means necessary ' , 
' BAO ':' be aware of ' , 
' BAS ':' big a** smile ' , 
' BAU ':' business as usual ' , 
' BB ':' be back/big brother/baby ' , 
' BBAM ':' be back after meal ' , 
' BBB ':' bugging beyond belief ' , 
' BBEG ':' big bag evil guy ' , 
' BBFL ':' best buds for life ' , 
' BBFN ':' bye bye for now ' , 
' BBG ':' best be going ' , 
' BBIAB ':' be back in a bit ' , 
' BBIAF ':' be back in a few ' , 
' BBIAM ':' be back in a minute ' , 
' BBIAS ':' be back in a second ' , 
' BBK ':' boy better know ' , 
' BBL ':' be back later ' , 
' BBM ':' Blackberry messaging ' , 
' BBML ':' be back much later ' , 
' BBN ':' bye bye now/be back never ' , 
' BBS ':' be back soon ' , 
' BBT ':' be back tomorrow ' , 
' BBWL ':' be back way later ' , 
' BCD ':' behind closed doors ' , 
' BCNU ':' be seeing you ' , 
' BCOS ':' because ' , 
' BD ':' big deal ' , 
' BDOML ':' best day of my life ' , 
' BEF ':' best enemies forever/best email friend ' , 
' BEG ':' big evil grin ' , 
' BF ':' boyfriend/best friend ' , 
' BF4L ':' best friends for life ' , 
' BFA ':' best friends always ' , 
' BFAM ':' brother from another mother ' , 
' BFD ':' big f***ing deal ' , 
' BFF ':' best friends forever/big fat friend/female ' , 
' BFF4L ':' best friends forever for life ' , 
' BFFAE ':' best friends forever and ever/for all eternity ' , 
' BFFE ':' best friends forever ' , 
' BFFL ':' best friends for life ' , 
' BFFLE ':' best friend for like ever ' , 
' BFFLTDDUP ':' best friends for life till death do us part ' , 
' BFFN ':' best friend for now ' , 
' BFFWB ':' best friend forever with benefits ' , 
' BFK ':' big fat kiss ' , 
' BFN ':' bye for now ' , 
' BFP ':' bad for pictures/big fat positive (ie pregnant) ' , 
' BFTP ':' blast from the past ' , 
' BFUT ':' best friends until tomorrow ' , 
' BFWB ':' best friend with benefits ' , 
' BG ':' big grin ' , 
' BGD ':' background ' , 
' BGF ':' best girl/guy friend ' , 
' BH ':' be happy/bloody hell/big head ' , 
' BHD ':' bad hair day ' , 
' BHH ':' bless his/her heart ' , 
' BIAB ':' back in a bit ' , 
' BIBO ':' beer in or beer out ' , 
' BIC ':' believe it comrade ' , 
' BICBW ':' but I could be wrong ' , 
' BIEH ':' best I ever had ' , 
' BIFFL ':' best Internet friend for life ' , 
' BIN ':' buy it now ' , 
' BION ':' believe it or not ' , 
' BIOYIOP ':' blow it out your I/O port ' , 
' BISLY ':' but I still love you ' , 
' BKA ':' better know as ' , 
' BL ':' belly laughing/bottom line/bad luck ' , 
' BLD ':' bad life decision ' , 
' BLOL ':' big laugh out loud ' , 
' BLTN ':' better late than never ' , 
' BLUF ':' bottom line up front ' , 
' BM4L ':' best mates for life ' , 
' BMBO ':' blow my brains out ' , 
' BMFE ':' best mates forever ' , 
' BMFL ':' best mates for life ' , 
' BMG ':' be my guest ' , 
' BMGWL ':' busting my gut with laughter ' , 
' BML ':' bless my life ' , 
' BMOC ':' big man on campus ' , 
' BMT ':' before my time/basic military training ' , 
' BMUS ':' beam me up or Scotty ' , 
' BNF ':' big name fan ' , 
' BNI ':' batteries not included ' , 
' BNIB ':' brand new in box ' , 
' BNR ':' but not really ' , 
' BOGOF ':' buy one get one free ' , 
' BOGSAT ':' bunch of guys sitting around talking ' , 
' BOL ':' best of luck ' , 
' BOOMM ':' bored out of my mind ' , 
' BOS ':' boyfriend over shoulder ' , 
' BOT ':' back on topic ' , 
' BOTEC ':' back of the envelope calculation ' , 
' BOTTS ':' back on to the subject ' , 
' BR ':' best regards ' , 
' BRB ':' be right back ' , 
' BRGDS ':' best regards ' , 
' BRH ':' be right here ' , 
' BRT ':' be right there ' , 
' BSF ':' but seriously folks ' , 
' BSOD ':' blue screen of death (MS Windows) ' , 
' BSOF ':' big smile on face ' , 
' BSOFN ':' big smile of face now ' , 
' BST ':' but seriously though ' , 
' BSTS ':' better safe than sorry ' , 
' BSU ':' boring status update ' , 
' BTA ':' but then again  ' , 
' BTAIM ':' be that as it may ' , 
' BTB ':' by the by ' , 
' BTD ':' bored to death ' , 
' BTDT ':' been there or done that ' , 
' BTDTGTTSAWIO ':' been there or done that or got the T-shirt and wore it out ' , 
' BTE ':' best time ever ' , 
' BTGOG ':' by the grace of God ' , 
' BTHOM ':' beats the hell out of me ' , 
' BTL ':' between the lines ' , 
' BTS ':' be there soon ' , 
' BTT ':' bump to top (forum posts) ' , 
' BTW ':' by the way ' , 
' BTWITIAILWU or BTWITIAILWY ':' by the way or I think I m in love with you ' , 
' BTY ':' back to you ' , 
' BU ':' backup ' , 
' BU2M ':' been up to much? ' , 
' BV ':' bad vibe ' , 
' BWL ':' bursting with laughter ' , 
' BWN ':' between ' , 
' BWTH ':' but what the hell ' , 
' BWTHDIK ':' but what the heck do I know? ' , 
' BYAM ':' between you and me ' , 
' BYKI ':' before you know it ' , 
' BYO ':' bring your own ' , 
' BYT ':' before your time ' , 
' BTYM ':' better you than me ' , 
' C ':' see ' , 
' C&G ':' chuckle and grin ' , 
' C/D ':' confirm/deny ' , 
' CBB ':' can t be bothered ' , 
' CC ':' carbon copy ' , 
' CCL ':' couldn t care less ' , 
' CDP ':' calm down please ' , 
' CFN ':' ciao for now ' , 
' CFV ':' call for votes ' , 
' CHK ':' check ' , 
' CICO ':' coffee in or coffee out ' , 
' CIHY ':' can I help you? ' , 
' CIO ':' check it out ' , 
' CITA ':' caught in the act ' , 
' CL ':' chain letter/Craig s List ' , 
' CLD ':' could ' , 
' CLK ':' click ' , 
' CLM ':' career limiting move ' , 
' CM ':' call me ' , 
' CMAR ':' cry me a river ' , 
' CMB ':' call me back ' , 
' CMEO ':' crying my eyes out ' , 
' CMI ':' count me in ' , 
' CMIIW ':' correct me if I m wrong ' , 
' CML ':' call me later ' , 
' CMN ':' come on ' , 
' CMNT or CMT ':' comment ' , 
' CMU ':' cracks me up ' , 
' CNP ':' continued in next post ' , 
' COL ':' crying out loud ' , 
' COP ':' officer of the law/close of play ' , 
' COS or COZ ':' because ' , 
' CP ':' Child Pornography ' , 
' CQB ':' close quarters battle ' , 
' CRB ':' come right back ' , 
' CRBT ':' crying really big tears ' , 
' CRC ':' chat room chuckle ' , 
' CRE8 ':' create ' , 
' CRUNK ':' crazy and drunk ' , 
' CSA ':' cheap shot artist ' , 
' CSL ':' can t stop laughing ' , 
' CTM ':' chuckling to myself ' , 
' CTN ':' can not talk now ' , 
' CTO ':' check this out ' , 
' CTRN ':' can not talk right now ' , 
' CTS ':' chuckles to self ' , 
' CU ':' see you ' , 
' CUIAB ':' see you in a bit ' , 
' CUL ':' see you later ' , 
' CUL8ER or CUL8R ':' see you later ' , 
' CUS ':' see you soon/friend ' , 
' CUT ':' see you tomorrow ' , 
' CUZ ':' because ' , 
' CWOT ':' complete waste of time ' , 
' CWTCU ':' can not wait to see you ' , 
' CWTSY ':' can not wait to see you ' , 
' CWYL ':' chat with you later ' , 
' CYA ':' see ya/cover you re a** ' , 
' CYB ':' count your blessings ' , 
' CYBI ':' can you believe it? ' , 
' CYE ':' check your email ' , 
' CYL ':' catch you later ' , 
' CYL8R ':' see you later ' , 
' CYM ':' check you mail ' , 
' CYO ':' see you online ' , 
' CYT ':' see you tomorrow ' , 
' D&M ':' deep and meaningful ' , 
' D/C ':' disconnected ' , 
' D2M ':' dead to me ' , 
' D8 ':' date ' , 
' DA ':' the ' , 
' DADT ':' do not ask or don t tell ' , 
' DAE ':' does anybody else ? ' , 
' DAM ':' do not ask me ' , 
' DAMHIK (T) ':' do not ask me how I know (this/that) ' , 
' DAQ ':' do not ask questions ' , 
' DB ':' douche bag ' , 
' DBA ':' doing business as ' , 
' DBI ':' douche bag index ' , 
' DBNT ':' do not bother next tie ' , 
' DBR ':' damaged beyond repair ' , 
' DC ':' do not care ' , 
' DCOI ':' do not count on it ' , 
' DDB ':' deaf or dumb or blind ' , 
' DDF ':' drug and disease free ' , 
' DDI ':' do not do it ' , 
' DDT ':' do not do that ' , 
' DEAR ':' drop everything and read ' , 
' DEB ':' do not even bother ' , 
' DEETS ':' details ' , 
' DEGT ':' do not even go there ' , 
' DETAI ':' do not even think about it ' , 
' DEU ':' defective end user ' , 
' DFLA ':' disenhanced four-letter acronym (meaning it s a TLA) ' , 
' DFS ':' dating for sport ' , 
' DFTBA ':' do not forget to be awesome ' , 
' DFTT ':' do not feed the troll ' , 
' DFW ':' down for whatever ' , 
' DG ':' do not go ' , 
' DGOT ':' do not go over there ' , 
' DGT ':' do not go there ' , 
' DGTWM ':' do not go there with me ' , 
' DHYB ':' do not hold your breath ' , 
' DIAF ':' die in a fire ' , 
' DIC ':' do I care? ' , 
' DIKU or DIKY ':' do I know you? ' , 
' DILLIC ':' does it look like I care? ' , 
' DILLIGAD ':' do I look like I give a darn? ' , 
' DIS ':' did I say ' , 
' DIT ':' details in thread ' , 
' DITD ':' down in the dumps ' , 
' DITYID ':' did I tell you I m depressed? ' , 
' DIY ':' do it yourself ' , 
' DJM ':' do not judge me ' , 
' DK ':' do not know ' , 
' DKDC ':' don t know or don t care ' , 
' DKFS ':' do not know for sure ' , 
' DKM ':' do not kill me ' , 
' DKY ':' do not know yet/don t kid yourself ' , 
' DL ':' dead link ' , 
' DL ':' download/down low ' , 
' DLAM ':' do not laugh at me ' , 
' DLC ':' downloadable content ' , 
' DLS ':' dirty little secret ' , 
' DLTBBB ':' do not let the bed bugs bite ' , 
' DLTM ':' do not lie to me ' , 
' DM ':' direct message/don t mind/doesn t matter ' , 
' DMAF ':' do not make a fuss ' , 
' DMAL ':' drop me a line ' , 
' DMC ':' deep meaningful conversation ' , 
' DMG ':' damage ' , 
' DMI ':' do not mention it ' , 
' DMIID ':' do not mind if I do ' , 
' DMTA ':' dirty minds think alike ' , 
' DMW ':' dead man walking ' , 
' DMY ':' do not mess yourself ' , 
' DN ':' doing nothing ' , 
' DND ':' do not disturb ' , 
' DNDC ':' do not know or do not care ' , 
' DNF ':' did not finish ' , 
' DNFTT ':' do not feed the trolls ' , 
' DNK ':' do not know ' , 
' DNM ':' does not matter/deep and meaningful ' , 
' DNO ':' do not know ' , 
' DNR ':' do not resuscitate ' , 
' DNS ':' domain name service/did not start ' , 
' DNT ':' do not ' , 
' DNW ':' do not want ' , 
' DOD ':' day of defeat ' , 
' DOE ':' depends on experience ' , 
' DOF ':' depth of field ' , 
' DOL ':' dying of laughter ' , 
' DOM ':' dirty old man ' , 
' DOS ':' dozing off soon/Dad over shoulder/disk operating system ' , 
' DOT ':' damage over time ' , 
' DPI ':' dots per inch/don t push it ' , 
' DPYN ':' do not pick your onse ' , 
' DQ ':' disqualified ' , 
' DQMOT ':' do not quote me on this ' , 
' DQYDJ ':' do not quit your day job ' , 
' DR ':' double rainbow ' , 
' DRT ':' dead right there ' , 
' DSD ':' do some damage ' , 
' DT ':' downtown ' , 
' DTA ':' do not trust anyone ' , 
' DTB ':' do not test back ' , 
' DTC ':' down to cuddle ' , 
' DTD ':' drunk till dawn/death ' , 
' DTE ':' down to earth ' , 
' DTMS ':' does the make sense? ' , 
' DTP ':' disturbing the peace ' , 
' DTR ':' define the relationship ' , 
' DTRT ':' do the right thing ' , 
' DTT ':' do not touch that ' , 
' DTTM ':' do not talk to me ' , 
' DTYT ':' do not take your time ' , 
' DUCWIC ':' do you see what I see? ' , 
' DUCY ':' do you see why? ' , 
' DULM ':' do you love me? ' , 
' DW ':' do not worry ' , 
' DWAI ':' do not worry about it ' , 
' DWB ':' do not write back ' , 
' DWB ':' driving while black ' , 
' DWBH ':' do not worry or be happy ' , 
' DWBI ':' do not worry  bout it ' , 
' DWI ':' deal with it ' , 
' DWISNWID ':' do what I say or not what I do ' , 
' DWL ':' dying with laughter ' , 
' DWMT ':' don t waste my time ' , 
' DWP ':' drunk while posting ' , 
' DWT ':' driving while texting ' , 
' DWU ':' don\'t wait up ' , 
' DYHWIH ':' do you hear what I hear? ' , 
' DYJ ':' do your job ' , 
' DYJHIW ':' don\'t you just have it when ? ' , 
' DYK ':' do you know? ' , 
' DYKWIM ':' do you know what I mean? ' , 
' DYLM ':' do you love/like me? ' , 
' DYM ':' do you mind?/do you mean? ' , 
' DYOR ':' do your own research ' , 
' E&OE ':' errors and omissions excluded ' , 
' E2E ':' end to end or exchange to exchange or e-business to e-business or employee to employee ',
' E2EG ':' ear to ear grin ' , 
' EB ':' eyebll ' , 
' EBCAK ':' error between chair and keyboard ' , 
' EEG ':' extremely evil grin ' , 
' EFA ':' edited for accuracy ' , 
' EFG ':' epic fall guy ' , 
' EG ':' evil grin ' , 
' EI ':' eat it ' , 
' ELE ':' everybody love everybody ' , 
' ELOL ':' evil laugh out loud ' , 
' EM ':' email ' , 
' EMA ':' email address ' , 
' EMFBI ':' excuse me for butting in ' , 
' EML ':' email ' , 
' EMSG ':' email message ' , 
' EOC ':' end of conversation ' , 
' EOD ':' end of discussion ' , 
' EOF ':' end of file ' , 
' EOG ':' end of grade ' , 
' EOL ':' end of lecture ' , 
' EOM ':' end of message ' , 
' EOR ':' end of rant ' , 
' EOS ':' enf of show ' , 
' EOT ':' end of thread (discussion) ' , 
' EOTW ':' end of the world ' , 
' EOTWAWKI ':' end of the world as we know it ' , 
' EQE ':' easy quick efficient ' , 
' ESAD ':' eat s**t and die ' , 
' ETLA ':' extended three-letter acronym (meaning a FLA) ' , 
' ETW ':' enjoy the weekend ' , 
' EUA ':' end user agreement ' , 
' EUC ':' excellent used condition ' , 
' EV ':' expected value ' , 
' EVL ':' evil laugh ' , 
' EWG ':' evil wicked grin ' , 
' F@ ':' fat ' , 
' F2F ':' face to face ' , 
' F2T ':' free to talk ' , 
' F4E ':' friends forever ' , 
' F8 ':' fate ' , 
' F9 ':' fine ' , 
' FAAK ':' falling asleep at keyboard ' , 
' FAB ':' fabulous ' , 
' FAFWOA ':' for a friend without access (when about to ask a silly question) ' , 
' FAI ':' forget about it ' , 
' FAO ':' for attention of ' , 
' FAQ ':' frequently asked questions ' , 
' FAV ':' favorite ' , 
' FAVE ':' favorite ' , 
' FB ':' Facebook ' , 
' FBC ':' Facebook chat ' , 
' FBF ':' Facebook friend ' , 
' FBM ':' fine by me ' , 
' FBO ':' Facebook official ' , 
' FBTW ':' fine or be that way ' , 
' FBW ':' fly by wire ' , 
' FC ':' fingers crossed ' , 
' FCFS ':' first come or first served ' , 
' FCOL ':' for crying out loud ' , 
' FCS ':' for Christ s sake ' , 
' FE ':' fair enough ' , 
' FEAE ':' for ever and ever ' , 
' FF ':' follow Friday (slang - recommendation to follow someone referenced in the tweet) ' , 
' FFA ':' free for all ' , 
' FFR ':' for future reference ' , 
' FFS ':' for f**k s sake ' , 
' FGS ':' for God s sake ' , 
' FHE ':' first hand experience ' , 
' FI ':' forget it ' , 
' FIFO ':' first in or first out ' , 
' FIFY ':' fixed it for you ' , 
' FILO ':' first in or last out ' , 
' FIO ':' figure it out ' , 
' FISH ':' first in or still here ' , 
' FITB ':' fill in the blanks ' , 
' FKA ':' formerly know as ' , 
' FL ':' fake laugh ' , 
' FLA ':' four-letter acronym ' , 
' FLK ':' funny looking kid ' , 
' FMDIDGAD ':' frankly my dear or I don t give a damn ' , 
' FMI ':' for more information ' , 
' FML ':' f*** my life ' , 
' FMTKFYTFO ':' for me to know or for you to find out ' , 
' FMTYEWTK ':' far more than you ever wanted to know ' , 
' FMV ':' full motion video ' , 
' FNA ':' for necessary action ' , 
' FNB ':' football and beer ' , 
' FNE ':' free and easy ' , 
' FNO ':' from now on ' , 
' FOA ':' first of all ' , 
' FOAF ':' friend of a friend ' , 
' FOC ':' free of charge ' , 
' FOFL ':' falling on floor laughing ' , 
' FOFO ':' .44 cal pistol ' , 
' FOMCL or FOCL ':' falling off my chair laughing ' , 
' FOMO ':' fear of missing out ' , 
' FON ':' freak of nature ' , 
' FOTM ':' flavor of the month ' , 
' FP ':' face palm (as in putting hand over face in dismay ' , 
' FR ':' for real ' , 
' FRS ':' freight ' , 
' FRAP ':' Facebook rape - vandalizing someone s Facebook page ' , 
' FSHO ':' for sure ' , 
' FSOT ':' for sale or trade ' , 
' FSR ':' for some reason ' , 
' FTA ':' form the article ' , 
' FTASB ':' faster than a speeding bullet ' , 
' FTBOMH ':' from the bottom of my heart ' , 
' FTF ':' face-to-face ' , 
' FTFY ':' fixed that for you ' , 
' FTL ':' for the loss/lose ' , 
' FTLOG ':' for the love of God ' , 
' FTR ':' for the record ' , 
' FTTB ':' for the time being ' , 
' FTW ':' F*** the world ' , 
' FTW ':' for the win ' , 
' FUBAR ':' fouled up beyond all recognition ' , 
' FUD ':' fear or uncertainty or and doubt ' , 
' FWD ':' forward ' , 
' FWIW ':' for what it \' s worth ' , 
' FWTD ':' fate worse than death ' , 
' FX ':' effects ' , 
' FYA ':' for your amusement ' , 
' FYE ':' for your entertainment ' , 
' FYEO ':' for your eyes only ' , 
' FYI ':' for your information ' , 
' FYM ':' free your mind ' , 
' FYN ':' fine ' , 
' FYP ':' fixed your post ' , 
' FYR ':' for your review/for your records ' , 
' G ':' grin ' , 
' G2B ':' go to bed ' , 
' G2E ':' got to eat ' , 
' G2F ':' got to fly ' , 
' G2G ':' got to go ' , 
' G2G2B ':' got to go to bed ' , 
' G2H ':' go to hell ' , 
' G2R ':' got to run ' , 
' G2S ':' go to sleep ' , 
' G4U ':' good for you ' , 
' GA ':' go ahead ' , 
' GAC ':' guilty as charged/get a clue ' , 
' GAFIA ':' get away from it all ' , 
' GAFM ':' get away from me ' , 
' GAJ ':' get a job ' , 
' GAL ':' get a life ' , 
' GAMMD ':' go ahead or make my day ' , 
' GBFN ':' goodbye for now ' , 
' GBH ':' grievous bodily harm ' , 
' GBML ':' goodbye my love ' , 
' GBNF ':' gone but not forgotten ' , 
' GBTW ':' get back to work ' , 
' GBU ':' God bless you ' ,
' GBY ':' God bless you ' , 
' GCF ':' good clean fun ' , 
' GD&R ':' grinning or ducking and running ' , 
' GDAY ':' hi/good day ' , 
' GDI ':' G** damn it ' , 
' GE ':' good evening ' , 
' GF ':' girlfriend ' , 
' GFAK ':' go fly a kite ' , 
' GFETE ':' grinning from ear to ear ' , 
' GFI ':' go for it ' , 
' GFN ':' gone for now ' , 
' GFU ':' good for you ', 
' GFY ':' good for you ' } 

def remSF(text):
   def replace_all(text, dic):
       for i, j in dic.items():
           text = text.replace(i, j)
           #print (text)
       return text
   text = replace_all(text, w_dict)
   # print result
   return text
